//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InvoicesTmsDbEntities : DbContext
    {
        public InvoicesTmsDbEntities()
            : base("name=InvoicesTmsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetInvoiveByCustomer_Result> GetInvoiveByCustomer(Nullable<int> customer_Num, Nullable<System.DateTime> formDate, Nullable<System.DateTime> tOdate)
        {
            var customer_NumParameter = customer_Num.HasValue ?
                new ObjectParameter("Customer_Num", customer_Num) :
                new ObjectParameter("Customer_Num", typeof(int));
    
            var formDateParameter = formDate.HasValue ?
                new ObjectParameter("FormDate", formDate) :
                new ObjectParameter("FormDate", typeof(System.DateTime));
    
            var tOdateParameter = tOdate.HasValue ?
                new ObjectParameter("TOdate", tOdate) :
                new ObjectParameter("TOdate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetInvoiveByCustomer_Result>("GetInvoiveByCustomer", customer_NumParameter, formDateParameter, tOdateParameter);
        }
    }
}
