//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipp
    {
        public int Shipp_Num { get; set; }
        public System.DateTime Shipp_Date_Time { get; set; }
        public Nullable<int> Employee_Number { get; set; }
        public Nullable<int> Customer_Number { get; set; }
        public string Transaction_Number { get; set; }
        public string Vehicle_Number { get; set; }
        public string Shipp_Origin { get; set; }
        public string Shipp_Dest { get; set; }
        public int Shipp_Quantity { get; set; }
        public decimal Shipp_Amount { get; set; }
        public string Shipp_DocNum { get; set; }
    }
}
